model_name: "dimenet"

emb_size: 128
num_blocks: 6

num_bilinear: 8
num_spherical: 7
num_radial: 6
output_init: 'GlorotOrthogonal'  # 'zeros' for Mu, HOMO, LUMO, and ZPVE; 'GlorotOrthogonal' for alpha, R2, U0, U, H, G, and Cv

cutoff: 5.0
envelope_exponent: 5

num_before_skip: 1
num_after_skip: 2
num_dense_output: 3

num_train: 1000
num_valid: 10000
data_seed: 42
dataset: "data/md17_aspirin.npz"
logdir: "."

num_steps: 3000000
ema_decay: 0.999

learning_rate: 0.001
warmup_steps: 3000
decay_rate: 0.01
decay_steps: 4000000

batch_size: 32
evaluation_interval: 10000
save_interval: 10000
restart: None
comment: "final"
targets: ['E']  # ['mu', 'alpha', 'homo', 'lumo', 'gap', 'r2', 'zpve', 'U0', 'U', 'H', 'G', 'Cv']
